default: &default
  adapter: postgresql
  encoding: unicode
  username: billy
  password:
  pool: 5

development:
  <<: *default
  database: Ruby_Project_development

test:
  <<: *default
  database: Ruby_Project_test


production:
  <<: *default
  database: Ruby_Project_production
  # username: Ruby_Project
  # password: <%= ENV['RUBY_PROJECT_DATABASE_PASSWORD'] %>
